### ISSUE TITLE
SKIP_SMOKE_TESTS doesnt accept namespaces

### ISSUE THREAD

**Issue by jayvdb** [kamilkijak/django-smoke-tests#14]
* django-smoke-tests version: master++
* Django version: 3.0.7
* Python version: 3.8
* Operating System: openSUSE Tumbleweed

### Description

I am using django-oscar , which has a bunch of failures across its many constituted apps, including the following three views
```
'dashboard:catalogue-attribute-option-group-create',
'dashboard:catalogue-class-create',
'dashboard:catalogue-product-create',
```

However, I need to omit the namespace when I put them into `SKIP_SMOKE_TESTS`.
i.e.
```
'catalogue-attribute-option-group-create',
'catalogue-class-create',
'catalogue-product-create',
```

There are others like `'customer:order'` which need to become `'order'`.
I am sure that I will have a few cases of view names which need a namespace in order to be distinct, but I guess the skip would apply to all with the same name, so that outcome isnt terrible.

However more importantly, it took me a while to recognise that the namespace needed to be omitted.  A quick README update would be helpful, if a proper solution isnt easy.

**Comment by kamilkijak** [comment]
Related to https://github.com/kamilkijak/django-smoke-tests/issues/17.

It has been fixed in v2.0.0. Thanks @jayvdb!
