### ISSUE TITLE
Path args used in literal path fetchs

### ISSUE THREAD

**Issue by jayvdb** [kamilkijak/django-smoke-tests#15]
* django-smoke-tests version: master

```
[00:45:56][WARNING] django.request log.py:log_response:228 | Not Found: /admin/doc/views/<view>/
F[00:45:56][WARNING] django.request log.py:log_response:228 | Not Found: /admin/r/<int:content_type_id>/<path:object_id>/
F
```

django-smoke-tests should skip views where it can not figure out how to construct a valid URL.

**Comment by kamilkijak** [comment]
Thanks for reporting! I was able to reproduce the problem you've shared with a unit test (they're becoming too complex to call them unit tests). It's fixed now.

> where it can not figure out how to construct a valid URL

Right, this might be a good idea. I imagine we could use something like [validators.url](https://validators.readthedocs.io/en/latest/#module-validators.url) to tell if it's properly generated. It would've worked in your case (eg. there's illegal characters like `:` or `<`). We'd also need to make sure we don't just fail silently, so we can fix if there's a bug - like in your case. Thanks again!
