### ISSUE TITLE
SKIP_SMOKE_TESTS ignored

### ISSUE THREAD

**Issue by chrisspen** [kamilkijak/django-smoke-tests#17]
This may be more a request for documentation, but it's unclear what the format of `SKIP_SMOKE_TESTS` should be.

How do you specify a URL to ignore? The README implies it should be the same name that's accepted by `reverse()`, but this doesn't seem to be true.

For example, `smoke_tests` currently complains about `/admin/myapp/mymodel/add/` with the notorious error:

     django.core.exceptions.ValidationError: ['ManagementForm data is missing or has been tampered with']

The traceback returned touches none of my own code, so there's no way for me to fix this, so I'd like `smoke_tests` to skip this path.

You'd think adding `admin:myapp_mymodel_add` to the `SKIP_SMOKE_TESTS` list would skip this path, but it has no effect. I've tried all of these patterns:

    'admin:myapp_mymodel_add'
    '^admin/myapp/mymodel/add/'
    '/admin/myapp/mymodel/add/'
    '/admin/myapp/mymodel/add'

and none of them skip that path.

**Comment by kamilkijak** [comment]
Thank you @chrisspen, there was a bug in the code. A fix has been released in v2.0.0, let me know if you have any other issues.
